name: Accessibility Scanner

on:
  workflow_run:
    workflows: ["Azure Static Web Apps CI/CD"]
    types:
      - completed
  workflow_dispatch:

jobs:
  accessibility_scanner:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: github/accessibility-scanner@v2
        with:
          urls: |
            https://www.cognitiveinheritance.com
          repository: bsstahl/CognitiveInheritance
          token: ${{ secrets.GH_TOKEN }}
          cache_key: docs-a11y-scan
